name: smart_parking_app
description: A smart parking system application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.0
  mobile_scanner: ^3.5.6  # Using mobile_scanner instead of qr_code_scanner

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true